name: animequiz
description: Anime Quiz

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: any

  cupertino_icons: ^0.1.3

  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/home.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
     - assets/sounds/correct.mp3
     - assets/sounds/wrong.mp3
     - assets/
     - assets/naruto/
     - assets/narutoS/
     - assets/ft/

  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf

    - family: LondrinaSolid
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf

    - family: ArchitectsDaughter
      fonts:
            - asset: assets/fonts/ArchitectsDaughter-Regular.ttf

    - family: SourceSansPro
      fonts:
            - asset: assets/fonts/SourceSansPro-Light.ttf
            - asset: assets/fonts/SourceSansPro-Bold.ttf
              weight: 700
            - asset: assets/fonts/SourceSansPro-SemiBold.ttf
              weight: 500